/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package log4kt

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        log.v("Hi")
        log.d("Hi")
        Thread.sleep(1000)
        log.i("Hi")
        val logger = Logger("Logger") { level, tag, msg ->
            println("$tag - [$level] - $msg")
        }
        logger.w("Hi")
        logger.e("Hi")
    }
}
